version: '3'

services:
  nodecryptocompare:
    build: .
    image: node/cryptocompare:latest
    container_name: sboot_cryptocompare
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
